window:
  opacity: 0.7
# Font configuration (changes require restart)
font:
  size: 9.5
  normal:
    family: SauceCodeProNerdFont
    style: Regular

  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

scrolling:
  history: 100000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier: 3

key_bindings:
  - { key: PageUp, action: ScrollPageUp }
  - { key: PageDown, action: ScrollPageDown }
  - { key: End, action: ScrollToBottom }
  - { key: Home, action: ScrollToTop }
